// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkqbmrjdegyiogkgooab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprcWJtcmpkZWd5aW9na2dvb2FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMTA1OTUsImV4cCI6MjA2Nzg4NjU5NX0.aFx8_9UotifF5NB5Te3BBC57JVn3N5OaccAILPrNZCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});